apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-desktop
  labels:
    app: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
        - name: docker-desktop
          image: vipv/kuber
          ports:
            - containerPort: 3000
